# Generated by Django 4.2.7 on 2023-11-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_studentposition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentPosition',
        ),
    ]
